apiVersion: apps/v1
kind: Deployment
metadata:
  name: diceroll
spec:
  selector:
    matchLabels:
      app: diceroll
  template:
    metadata:
      labels:
        app: diceroll
    spec:
      tolerations:
      nodeSelector:
      terminationGracePeriodSeconds: 5
      containers:
        - name: diceroll
          image: docker.io/library/diceroll:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          resources:
            requests:
              cpu: 110m
              memory: 90Mi
            limits:
              cpu: 130m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: diceroll
spec:
  type: NodePort
  selector:
    app: diceroll
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007